###########################################################################################
# 这是yml文件. 编辑的时候要小心一点. 要记得检查YAML语法   #
# 可以看看这里 http://yaml-online-parser.appspot.com                                        #
###########################################################################################
# 这是史诗空岛的配置文件
# 其他的配置文件请看plugin文件夹下的:
# - worlds.yml | schematics/configuration.yml | challenges.yml
---

## 不要修改这个
version: "MicroGitHub"

## 游戏前缀.
Prefix: "&d[&e史诗空岛&d] &e"
## 允许调试
debug: true
## 允许从GayHub获取更新
allowUpdate: false
## 语言
##  提供的语言有:
##    en_US - 英语 by larryTheCoder.
##    de_DE - 德语 by UnexMC
defaultlanguage: "en_US"
# 团队聊天
teamChat: true
# 开启快速下载. 这经常让插件进行
# 100ms 在插件加载之后. 很好但是在控制台看起来很难看
fastLoad: false
# 快速缓存
# 是否开启快速缓存
# N不是每个数据都有效地保存
# 这里很难找到bug (但是推荐不要使用)
fastCache: false

## 经济部分
economy:
  # 是否开启经济功能?
  # 你可以把这个设置为 'true' ，如果你有经济前置的话
  # 如果没有经济前置，这里会自动变为 'false'
  #  支持的经济前置有:
  #  - EconomyAPI
  enable: false
  # 开启空岛金钱
  #  决定创建第一个岛屿是否要付钱
  payNewIsland: false
  # 创建岛屿价格 $$$
  #  你不需要打 '$' 标识
  islandCost: 10

##### 空岛相关设置 #####
island:
  # 岛屿名字限制
  #   这里你可以限制
  #   岛屿名字的长度
  #   你可以写-1 来不启用
  nameLimit: 20
  # 岛屿重置
  #   这里你可以设置
  #   当玩家重置岛屿时的方块
  #   注意: 你设置得越高, 服务器性能需要越好
  chunkResetPerBlocks: 256
  # 这个特性在时间单位是秒
  # 不是分钟
  deleteTiming: 180
  #  这里写出示范指令格式
  #   比如`/example1, /example2`
  restrictedCommands: "/exampleCommand, /exampleCommand2"
  # 空岛重置
  # 你可以使用 -1 来不限制空岛重置
  reset: 3
  # 空岛游戏模式
  gamemode: 0
  # 空岛添加成员时间冷却
  #   你可以使用-1来不启用
  #   但是推荐20秒
  timeOut: 20
  # Island companion names
  #   Your passion to add this or nor
  #   Syntax: "&aFood?, &eEmergency Food?, &cYour Pet!"
  #  (Unavailable) 待翻译
  companionNames: "&aFood?, &eEmergency Food?, &cYour Pet!"
  # 物品设置
  items:
    # 玩家刚到岛屿时，箱子里的物品
    # 必须是Nukkit物品格式. 格式为 <ID>:<Qty> 或者<ID>:<Data>:<Qty>
    # 用 <Data> 来设置物品的耐久 或者来选择 附属物品/颜色
    #
    # 请设置 `USE_CONFIG_CHEST` 为True（在其他配置文件里
    # 这样就能正确读取配置.
    #
    # 检查控制台的报错 然后重载配置
    chestItems: 'ICE:2 MELON:1 TORCH:2 BONE:1 325:1:10 PUMPKIN_SEEDS:1 SUGAR_CANE:1 RED_MUSHROOM:1 BROWN_MUSHROOM:1 CACTUS:1 BREAD:1 WHEAT:1 LEATHER_BOOTS:1 LEATHER_HELMET:1 LEATHER_CHESTPLATE:1 LEATHER_LEGGINGS:1'

# 保护设置
# 一些特性可能不启用
protection:
  # 保护设置标签:
  # ACID_DAMAGE, ANVIL, BEACON, BED, BREAK_BLOCKS, BREEDING, BREWING,
  # BUCKET, COLLECT_LAVA, COLLECT_WATER, CHEST, CHORUS_FRUIT, CRAFTING, CROP_TRAMPLE,
  # DOOR, EGGS, ENCHANTING, ENDER_PEARL, ENTER_EXIT_MESSAGES, FIRE, FIRE_EXTINGUISH,
  # FIRE_SPREAD, FURNACE, GATE, HORSE_INVENTORY, HORSE_RIDING, HURT_MOBS, LEASH,
  # LEVER_BUTTON, MOB_SPAWN, PLACE_BLOCKS, PORTAL, PRESSURE_PLATE, PVP,
  # MILKING, NETHER_PVP, REDSTONE, SPAWN_EGGS, SHEARING, VILLAGER_TRADING,
  # VISITOR_ITEM_DROP, VISITOR_ITEM_PICKUP
  world:
    # 酸使海的伤害越来越大
    ACID_DAMAGE: true
    # 允许使用铁毡
    ANVIL: false
    # 允许使用信标
    BEACON: false
    # 允许使用床
    BED: false
    # 玩家可以破坏方块或者造成伤害
    BREAK_BLOCKS: false
    # 允许动物繁殖
    BREEDING: false
    # 允许使用坩埚和酿造台
    BREWING: false
    # 允许使用水桶，包括填满和倒出
    BUCKET: false
    # 收集岩浆
    COLLECT_LAVA: false
    # 收集水
    COLLECT_WATER: false
    # 允许任何类型的箱子，漏斗等
    CHEST: false
    # 允许吃水果
    CHORUS_FRUIT: false
    # 使用工作台
    CRAFTING: true
    # 苦力怕伤害玩家（不会破坏方块
    CREEPER_PAIN: true
    # 践踏作物
    CROP_TRAMPLE: false
    # 使用门，陷阱门，不包括红石设备.
    DOOR: true
    # 允许鸡下蛋
    EGGS: false
    # 使用附魔台
    ENCHANTING: true
    # 使用末影珍珠
    ENDER_PEARL: false
    # 开启或者关闭 join/leave 消息
    ENTER_EXIT_MESSAGES: true
    # 火焰燃烧.
    FIRE: false
    # 击打火焰来灭火
    FIRE_EXTINGUISH: false
    # 火焰传播
    FIRE_SPREAD: false
    # 使用熔炉
    FURNACE: true
    # 使用门
    GATE: false
    # 允许使用马/驼羊背包 - 只有骑上去的时候才有用
    HORSE_INVENTORY: false
    # 骑马/驼羊
    HORSE_RIDING: false
    # 攻击友好生物
    HURT_MOBS: false
    # 攻击怪物
    HURT_MONSTERS: true
    # 使用栓绳
    LEASH: false
    # 使用按钮和拉杆
    LEVER_BUTTON: true
    # 牛生产牛奶
    MILKING: true
    # 自然生成动物
    MOB_SPAWN: true
    # 自然生成怪物
    MONSTER_SPAWN: true
    # 在地狱PVP
    NETHER_PVP: false
    # 玩家放置方块
    PLACE_BLOCKS: false
    # 使用地狱入口
    PORTAL: true
    # 踩压力板
    PRESSURE_PLATE: true
    # 在世界PVP
    PVP: false
    # 红石比较器，红石中继器等物品使用
    REDSTONE: false
    # 生出的鸡蛋可以使用
    SPAWN_EGGS: false
    # 剪羊毛
    SHEARING: false
    # 与村名交易
    VILLAGER_TRADING: true
    # 物品掉落
    VISITOR_ITEM_DROP: true
    # 拾取物品
    VISITOR_ITEM_PICKUP: true
  # -- 岛屿设置 --
  # 岛屿设置，一些是给游客，一些是给岛屿本身.
  # 如果没有列出的设置, 它不会在GUI显示 ，开启世界默认模式.
  # 在这里添加设置，玩家就可以在GUI看到.
  # 给玩家这个权限，他们就可以修改设置.
  island:
    # 游客使用铁毡
    ANVIL: true
    # 游客使用信标
    BEACON: false
    # 游客使用床
    BED: false
    # 游客造成伤害。破坏方块
    BREAK_BLOCKS: false
    # 游客动物繁殖
    BREEDING: false
    # 游客使用坩埚和酿造台
    BREWING: false
    # 游客 使用箱子
    CHEST: false
    # 游客 使用工作台
    CRAFTING: true
    # 游客 使用门，陷阱门，不包括红石设备.
    DOOR: true
    # 鸡掉落鸡蛋
    EGGS: false
    # 游客 使用附魔台
    ENCHANTING: true
    # 游客使用熔炉
    FURNACE: true
    # 使用门
    GATE: true
    # 游客 使用地狱入口
    PORTAL: true
    # 游客使用压力板（玩家才能这么做
    PRESSURE_PLATE: false
    # 红石比较器，红石中继器等物品使用
    REDSTONE: false
    # 游客剪羊毛
    SHEARING: false

# 常规设置
general:
  # 传送冷却时间
  # 必须是int类型
  # 如果你不想用这个，写0
  islandTeleportDelay: 2
  # 传送取消移动距离
  # 玩家移动多远 传送取消
  teleportCancelDistance: 0.2
  # 公告消息
  broadcastmessages: true

database:
  connection: sqlite
  SQLite:
    # SQlite 文件名.
    # 你可以写你的名字
    # 你不需要在后面写 `.db`
    file-name: database
  MySQL:
    # 不启用
    port: 3306
    database: YourDataBase
    username: YourUserName
    password: 1234IsNotAGoodPassword
    host: localhost